name: HolographicChatEvo
version: 1.0
description: The perfect chat display
author: Claudiordev
softdepend: [HolographicDisplays]
main: com.claudiordev.main.Main
api-version: 1.15
commands:
  hdchat:
    description: Main plugin command
    usage: /hdchat